### ISSUE TITLE
Add stat effects (Easiest)

### ISSUE THREAD

**Issue by Pigges** [Pigges/so4#1]
**Description**
Currently, the player can increase their stats through various skills in the skill tree (Luck, Evasion, Shield Efficiency). Only some of these stats currently have an effect in the game (Shield Efficiency, Hull Mastery, and Evasion) However, many of these stats have no effect in the game. You should implement the remaining stats so that they provide actual bonuses. The stats that need to be implemented are: Luck, Energy Weapon Mastery, Kinetic Weapon Mastery, Missile Mastery.

**Comment by Dudeatron** [comment]
Fixed it at https://github.com/Pigges/so4/pull/5.

**Comment by Golijat** [comment]
Good job at fixing the issue Dudeatron, first issue and first to solve one of the issues, keep it up!
