### ISSUE TITLE
Fix player spinning during cutscenes (Medium)

### ISSUE THREAD

**Issue by Pigges** [Pigges/so4#2]
**Description**
Currently, when starting a cutscene, the player’s ship will keep its angular momentum and spin. It’s not really a bug, but the spinning looks pretty silly and breaks immersion during cutscenes. Make it so that the player’s ship doesn’t spin out of control during cutscenes, for example by cutting angular speed to 0.

**Comment by Golijat** [comment]
Fixed the issue by adding code in CObject.hxx and CObject.cxx. Also changed a few things with the controlls in CInSpaceState.cxx.

74baf08e5fe99babd445f3ed3abb6113075d1010
