### ISSUE TITLE
Add maximum range to skills (Medium)

### ISSUE THREAD

**Issue by Pigges** [Pigges/so4#3]
**Description**
Currently, certain target-based skills (Magnetic Drain, NavCom Virus) have infinite range. They should have limited range, so that the skills don’t work unless the player is sufficiently close to the target.

**Comment by Frrend** [comment]
Added an if statement for both Magnetic Drain and NavCom Virus. The if statements get the position of the caster and target and checks if the distance is less than 75.0f. If the distance is less than 75.0f the if condition is true and thus returns "false".
